#pragma once

#define MDLID_ARMOR 0x01 // progs/armor.mdl
#define MDLID_BACKPACK 0x02 // progs/backpack.mdl
#define MDLID_BOLT 0x03 // progs/bolt.mdl
#define MDLID_BOLT2 0x04 // progs/bolt2.mdl
#define MDLID_BOLT3 0x05 // progs/bolt3.mdl
#define MDLID_BOSS 0x06 // progs/boss.mdl
#define MDLID_DEMON 0x07 // progs/demon.mdl
#define MDLID_DOG 0x08 // progs/dog.mdl
#define MDLID_END1 0x09 // progs/end1.mdl
#define MDLID_EYES 0x0a // progs/eyes.mdl
#define MDLID_FLAME 0x0b // progs/flame.mdl
#define MDLID_FLAME2 0x0c // progs/flame2.mdl
#define MDLID_G_LIGHT 0x0d // progs/g_light.mdl
#define MDLID_G_NAIL 0x0e // progs/g_nail.mdl
#define MDLID_G_NAIL2 0x0f // progs/g_nail2.mdl
#define MDLID_G_ROCK 0x10 // progs/g_rock.mdl
#define MDLID_G_ROCK2 0x11 // progs/g_rock2.mdl
#define MDLID_G_SHOT 0x12 // progs/g_shot.mdl
#define MDLID_GIB1 0x13 // progs/gib1.mdl
#define MDLID_GRENADE 0x14 // progs/grenade.mdl
#define MDLID_INVISIBL 0x15 // progs/invisibl.mdl
#define MDLID_INVULNER 0x16 // progs/invulner.mdl
#define MDLID_KNIGHT 0x17 // progs/knight.mdl
#define MDLID_LAVABALL 0x18 // progs/lavaball.mdl
#define MDLID_M_G_KEY 0x19 // progs/m_g_key.mdl
#define MDLID_M_S_KEY 0x1a // progs/m_s_key.mdl
#define MDLID_MISSILE 0x1b // progs/missile.mdl
#define MDLID_OGRE 0x1c // progs/ogre.mdl
#define MDLID_PLAYER 0x1d // progs/player.mdl
#define MDLID_QUADDAMA 0x1e // progs/quaddama.mdl
#define MDLID_S_LIGHT 0x1f // progs/s_light.mdl
#define MDLID_S_SPIKE 0x20 // progs/s_spike.mdl
#define MDLID_SHAMBLER 0x21 // progs/shambler.mdl
#define MDLID_SOLDIER 0x22 // progs/soldier.mdl
#define MDLID_SPIKE 0x23 // progs/spike.mdl
#define MDLID_SUIT 0x24 // progs/suit.mdl
#define MDLID_V_AXE 0x25 // progs/v_axe.mdl
#define MDLID_V_LIGHT 0x26 // progs/v_light.mdl
#define MDLID_V_NAIL 0x27 // progs/v_nail.mdl
#define MDLID_V_NAIL2 0x28 // progs/v_nail2.mdl
#define MDLID_V_ROCK 0x29 // progs/v_rock.mdl
#define MDLID_V_ROCK2 0x2a // progs/v_rock2.mdl
#define MDLID_V_SHOT 0x2b // progs/v_shot.mdl
#define MDLID_V_SHOT2 0x2c // progs/v_shot2.mdl
#define MDLID_W_G_KEY 0x2d // progs/w_g_key.mdl
#define MDLID_W_S_KEY 0x2e // progs/w_s_key.mdl
#define MDLID_W_SPIKE 0x2f // progs/w_spike.mdl
#define MDLID_WIZARD 0x30 // progs/wizard.mdl
#define MDLID_ZOM_GIB 0x31 // progs/zom_gib.mdl
#define MDLID_ZOMBIE 0x32 // progs/zombie.mdl
#define MDLID_FISH 0x33 // progs/fish.mdl
#define MDLID_HKNIGHT 0x34 // progs/hknight.mdl
